ALTER TABLE products ADD COLUMN part_category_id INT NULL AFTER stock;

CREATE TABLE IF NOT EXISTS part_categories (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    slug VARCHAR(200) NOT NULL UNIQUE,
    parent_id INT NULL,
    icon VARCHAR(10) DEFAULT NULL,
    sort_order INT DEFAULT 0,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (parent_id) REFERENCES part_categories(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO part_categories (name, slug, parent_id, icon, sort_order) VALUES
('موتور و قطعات موتوری', 'engine-parts', NULL, '&#9881;', 1),
('جلوبندی و تعلیق', 'suspension', NULL, '&#9881;', 2),
('ترمز', 'brakes', NULL, '&#9881;', 3),
('بدنه و شاسی', 'body-chassis', NULL, '&#9881;', 4),
('برق و الکترونیک', 'electrical', NULL, '&#9881;', 5),
('گیربکس و انتقال قدرت', 'transmission', NULL, '&#9881;', 6),
('اگزوز', 'exhaust', NULL, '&#9881;', 7),
('سیستم سوخت‌رسانی', 'fuel-system', NULL, '&#9881;', 8),
('سیستم خنک‌کننده', 'cooling', NULL, '&#9881;', 9),
('لوازم داخلی', 'interior', NULL, '&#9881;', 10),
('چراغ و روشنایی', 'lighting', NULL, '&#9881;', 11),
('شیشه و آینه', 'glass-mirrors', NULL, '&#9881;', 12),
('لاستیک و چرخ', 'tires-wheels', NULL, '&#9881;', 13),
('روغن و مایعات', 'fluids', NULL, '&#9881;', 14);

INSERT INTO part_categories (name, slug, parent_id, sort_order) VALUES
('پیستون و رینگ', 'piston-rings', 1, 1),
('سرسیلندر و واشر', 'cylinder-head', 1, 2),
('تسمه تایم', 'timing-belt', 1, 3),
('شمع و کوئل', 'spark-coil', 1, 4),
('فیلتر روغن و هوا', 'filters', 1, 5),
('کمک فنر', 'shock-absorber', 2, 1),
('سیبک و بوش', 'bushings', 2, 2),
('فنر و تعلیق', 'springs', 2, 3),
('لنت ترمز', 'brake-pads', 3, 1),
('دیسک ترمز', 'brake-discs', 3, 2),
('پمپ ترمز و بوستر', 'brake-pump', 3, 3),
('کالیپر ترمز', 'brake-caliper', 3, 4),
('سپر و جلوپنجره', 'bumpers-grille', 4, 1),
('گلگیر و کاپوت', 'fenders-hood', 4, 2),
('درب و قطعات بدنه', 'doors-body', 4, 3),
('استارت و دینام', 'starter-alternator', 5, 1),
('باتری و کابل', 'battery-cables', 5, 2),
('سنسورها', 'sensors', 5, 3),
('کلاچ', 'clutch', 6, 1),
('گیربکس اتوماتیک', 'auto-transmission', 6, 2),
('پلوس و دیفرانسیل', 'axles-differential', 6, 3),
('منبع اگزوز', 'muffler', 7, 1),
('پمپ بنزین', 'fuel-pump', 8, 1),
('انژکتور', 'injector', 8, 2),
('رادیاتور', 'radiator', 9, 1),
('واتر پمپ', 'water-pump', 9, 2),
('فن خنک‌کننده', 'cooling-fan', 9, 3),
('داشبورد و رودری', 'dashboard', 10, 1),
('صندلی و کمربند', 'seats-belts', 10, 2),
('چراغ جلو و عقب', 'headlights-taillights', 11, 1),
('شیشه جلو و عقب', 'windshield', 12, 1),
('آینه بغل', 'side-mirrors', 12, 2),
('لاستیک', 'tires', 13, 1),
('رینگ و قالپاق', 'rims-hubcaps', 13, 2),
('روغن موتور', 'engine-oil', 14, 1),
('ضدیخ و آب رادیاتور', 'antifreeze', 14, 2);