<?php
function brandLogo($slug, $name, $size = 42) {
    $logos = [
        'ikco'           => '<svg viewBox="0 0 64 64" width="'.$size.'" height="'.$size.'"><circle cx="32" cy="32" r="30" fill="#003D7C"/><text x="32" y="41" text-anchor="middle" fill="#fff" font-size="22" font-weight="bold" font-family="Arial">IK</text></svg>',
        'saipa'          => '<svg viewBox="0 0 64 64" width="'.$size.'" height="'.$size.'"><circle cx="32" cy="32" r="30" fill="#E31837"/><text x="32" y="41" text-anchor="middle" fill="#fff" font-size="20" font-weight="bold" font-family="Arial">SP</text></svg>',
        'pars-khodro'    => '<svg viewBox="0 0 64 64" width="'.$size.'" height="'.$size.'"><circle cx="32" cy="32" r="30" fill="#1A5276"/><text x="32" y="41" text-anchor="middle" fill="#fff" font-size="18" font-weight="bold" font-family="Arial">PK</text></svg>',
        'kerman-motor'   => '<svg viewBox="0 0 64 64" width="'.$size.'" height="'.$size.'"><circle cx="32" cy="32" r="30" fill="#C0392B"/><text x="32" y="41" text-anchor="middle" fill="#fff" font-size="18" font-weight="bold" font-family="Arial">KM</text></svg>',
        'mvm'            => '<svg viewBox="0 0 64 64" width="'.$size.'" height="'.$size.'"><rect x="2" y="2" width="60" height="60" rx="14" fill="#0F2B46"/><text x="32" y="42" text-anchor="middle" fill="#D4AF37" font-size="24" font-weight="bold" font-family="Arial">MVM</text></svg>',
        'bahman-motor'   => '<svg viewBox="0 0 64 64" width="'.$size.'" height="'.$size.'"><circle cx="32" cy="32" r="30" fill="#2C3E50"/><text x="32" y="41" text-anchor="middle" fill="#F1C40F" font-size="18" font-weight="bold" font-family="Arial">BM</text></svg>',
        'zamyad'         => '<svg viewBox="0 0 64 64" width="'.$size.'" height="'.$size.'"><circle cx="32" cy="32" r="30" fill="#7F8C8D"/><text x="32" y="41" text-anchor="middle" fill="#fff" font-size="20" font-weight="bold" font-family="Arial">ZM</text></svg>',
        'bahman-group'   => '<svg viewBox="0 0 64 64" width="'.$size.'" height="'.$size.'"><circle cx="32" cy="32" r="30" fill="#2C3E50"/><text x="32" y="41" text-anchor="middle" fill="#F39C12" font-size="18" font-weight="bold" font-family="Arial">BG</text></svg>',
        'rayen'          => '<svg viewBox="0 0 64 64" width="'.$size.'" height="'.$size.'"><circle cx="32" cy="32" r="30" fill="#8E44AD"/><text x="32" y="41" text-anchor="middle" fill="#fff" font-size="20" font-weight="bold" font-family="Arial">RY</text></svg>',
        'kia'            => '<svg viewBox="0 0 64 64" width="'.$size.'" height="'.$size.'"><ellipse cx="32" cy="32" rx="30" ry="26" fill="#C41230"/><text x="32" y="42" text-anchor="middle" fill="#fff" font-size="28" font-weight="bold" font-family="Arial">KIA</text></svg>',
        'hyundai'        => '<svg viewBox="0 0 64 64" width="'.$size.'" height="'.$size.'"><ellipse cx="32" cy="34" rx="26" ry="20" fill="#003469" transform="rotate(-10,32,34)"/><text x="32" y="40" text-anchor="middle" fill="#fff" font-size="22" font-weight="bold" font-family="Arial">H</text></svg>',
        'toyota'         => '<svg viewBox="0 0 64 64" width="'.$size.'" height="'.$size.'"><ellipse cx="32" cy="30" rx="28" ry="18" fill="#C00"/><ellipse cx="32" cy="38" rx="28" ry="18" fill="#C00"/><text x="32" y="32" text-anchor="middle" fill="#fff" font-size="18" font-weight="bold" font-family="Arial">TOYOTA</text></svg>',
        'mitsubishi'     => '<svg viewBox="0 0 64 64" width="'.$size.'" height="'.$size.'"><polygon points="32,4 4,60 32,44 60,60" fill="#E60012"/><text x="32" y="36" text-anchor="middle" fill="#fff" font-size="10" font-weight="bold" font-family="Arial">MITSUBISHI</text></svg>',
        'nissan'         => '<svg viewBox="0 0 64 64" width="'.$size.'" height="'.$size.'"><circle cx="32" cy="32" r="28" fill="#C3002F"/><text x="32" y="38" text-anchor="middle" fill="#fff" font-size="28" font-weight="bold" font-family="Arial">N</text></svg>',
        'renault'        => '<svg viewBox="0 0 64 64" width="'.$size.'" height="'.$size.'"><rect x="4" y="12" width="56" height="40" rx="6" fill="#FFCC00"/><text x="32" y="40" text-anchor="middle" fill="#000" font-size="20" font-weight="bold" font-family="Arial">R</text></svg>',
        'peugeot'        => '<svg viewBox="0 0 64 64" width="'.$size.'" height="'.$size.'"><circle cx="32" cy="32" r="28" fill="#002D62"/><text x="32" y="42" text-anchor="middle" fill="#fff" font-size="24" font-weight="bold" font-family="Arial">P</text></svg>',
        'citroen'        => '<svg viewBox="0 0 64 64" width="'.$size.'" height="'.$size.'"><polygon points="32,6 6,56 32,40 58,56" fill="#DA291C"/><text x="32" y="38" text-anchor="middle" fill="#fff" font-size="11" font-weight="bold" font-family="Arial">CITROEN</text></svg>',
        'bmw'            => '<svg viewBox="0 0 64 64" width="'.$size.'" height="'.$size.'"><circle cx="32" cy="32" r="30" fill="#fff" stroke="#1C69D4" stroke-width="2"/><circle cx="32" cy="32" r="28" fill="#1C69D4"/><text x="32" y="42" text-anchor="middle" fill="#fff" font-size="26" font-weight="bold" font-family="Arial">BMW</text></svg>',
        'mercedes-benz'  => '<svg viewBox="0 0 64 64" width="'.$size.'" height="'.$size.'"><circle cx="32" cy="32" r="30" fill="#C0C0C0"/><text x="32" y="40" text-anchor="middle" fill="#000" font-size="26" font-weight="bold" font-family="Arial">&#9733;</text></svg>',
        'audi'           => '<svg viewBox="0 0 64 64" width="'.$size.'" height="'.$size.'"><circle cx="20" cy="32" r="8" fill="#000"/><circle cx="32" cy="32" r="8" fill="#000"/><circle cx="44" cy="32" r="8" fill="#000"/></svg>',
        'volkswagen'     => '<svg viewBox="0 0 64 64" width="'.$size.'" height="'.$size.'"><circle cx="32" cy="32" r="28" fill="#003F7F"/><text x="32" y="41" text-anchor="middle" fill="#fff" font-size="18" font-weight="bold" font-family="Arial">VW</text></svg>',
        'lifan'          => '<svg viewBox="0 0 64 64" width="'.$size.'" height="'.$size.'"><circle cx="32" cy="32" r="30" fill="#DA251D"/><text x="32" y="41" text-anchor="middle" fill="#fff" font-size="22" font-weight="bold" font-family="Arial">LF</text></svg>',
        'jac'            => '<svg viewBox="0 0 64 64" width="'.$size.'" height="'.$size.'"><rect x="2" y="2" width="60" height="60" rx="10" fill="#005BAC"/><text x="32" y="43" text-anchor="middle" fill="#fff" font-size="24" font-weight="bold" font-family="Arial">JAC</text></svg>',
        'chery'          => '<svg viewBox="0 0 64 64" width="'.$size.'" height="'.$size.'"><ellipse cx="32" cy="32" rx="30" ry="24" fill="#E60012"/><text x="32" y="40" text-anchor="middle" fill="#fff" font-size="18" font-weight="bold" font-family="Arial">CHERY</text></svg>',
        'gac'            => '<svg viewBox="0 0 64 64" width="'.$size.'" height="'.$size.'"><circle cx="32" cy="32" r="28" fill="#002C5E"/><text x="32" y="42" text-anchor="middle" fill="#C4A962" font-size="22" font-weight="bold" font-family="Arial">GAC</text></svg>',
        'byd'            => '<svg viewBox="0 0 64 64" width="'.$size.'" height="'.$size.'"><rect x="2" y="2" width="60" height="60" rx="8" fill="#E41B23"/><text x="32" y="43" text-anchor="middle" fill="#fff" font-size="24" font-weight="bold" font-family="Arial">BYD</text></svg>',
        'geely'          => '<svg viewBox="0 0 64 64" width="'.$size.'" height="'.$size.'"><circle cx="32" cy="32" r="28" fill="#003B71"/><text x="32" y="42" text-anchor="middle" fill="#fff" font-size="20" font-weight="bold" font-family="Arial">GE</text></svg>',
        'changan'        => '<svg viewBox="0 0 64 64" width="'.$size.'" height="'.$size.'"><circle cx="32" cy="32" r="28" fill="#003893"/><text x="32" y="42" text-anchor="middle" fill="#fff" font-size="18" font-weight="bold" font-family="Arial">CA</text></svg>',
        'haval'          => '<svg viewBox="0 0 64 64" width="'.$size.'" height="'.$size.'"><rect x="2" y="2" width="60" height="60" rx="6" fill="#C3000A"/><text x="32" y="43" text-anchor="middle" fill="#fff" font-size="20" font-weight="bold" font-family="Arial">HAVAL</text></svg>',
        'fonix'          => '<svg viewBox="0 0 64 64" width="'.$size.'" height="'.$size.'"><circle cx="32" cy="32" r="28" fill="#1B1B2F"/><text x="32" y="42" text-anchor="middle" fill="#E94560" font-size="18" font-weight="bold" font-family="Arial">FNX</text></svg>',
        'lamari'         => '<svg viewBox="0 0 64 64" width="'.$size.'" height="'.$size.'"><circle cx="32" cy="32" r="28" fill="#0D1B2A"/><text x="32" y="42" text-anchor="middle" fill="#F4A261" font-size="18" font-weight="bold" font-family="Arial">LMR</text></svg>',
        'tigard'         => '<svg viewBox="0 0 64 64" width="'.$size.'" height="'.$size.'"><circle cx="32" cy="32" r="28" fill="#264653"/><text x="32" y="42" text-anchor="middle" fill="#E9C46A" font-size="18" font-weight="bold" font-family="Arial">TGR</text></svg>',
        'skywell'        => '<svg viewBox="0 0 64 64" width="'.$size.'" height="'.$size.'"><circle cx="32" cy="32" r="28" fill="#1E90FF"/><text x="32" y="42" text-anchor="middle" fill="#fff" font-size="18" font-weight="bold" font-family="Arial">SKY</text></svg>',
        'kmc'            => '<svg viewBox="0 0 64 64" width="'.$size.'" height="'.$size.'"><rect x="2" y="2" width="60" height="60" rx="10" fill="#111"/><text x="32" y="43" text-anchor="middle" fill="#C00" font-size="24" font-weight="bold" font-family="Arial">KMC</text></svg>',
        'amico'          => '<svg viewBox="0 0 64 64" width="'.$size.'" height="'.$size.'"><circle cx="32" cy="32" r="28" fill="#D35400"/><text x="32" y="42" text-anchor="middle" fill="#fff" font-size="18" font-weight="bold" font-family="Arial">AMC</text></svg>',
        'farda'          => '<svg viewBox="0 0 64 64" width="'.$size.'" height="'.$size.'"><circle cx="32" cy="32" r="28" fill="#27AE60"/><text x="32" y="42" text-anchor="middle" fill="#fff" font-size="18" font-weight="bold" font-family="Arial">FRD</text></svg>',
        'soren'          => '<svg viewBox="0 0 64 64" width="'.$size.'" height="'.$size.'"><circle cx="32" cy="32" r="28" fill="#2C3E50"/><text x="32" y="42" text-anchor="middle" fill="#ECF0F1" font-size="18" font-weight="bold" font-family="Arial">SRN</text></svg>',
    ];

    if (isset($logos[$slug])) {
        return $logos[$slug];
    }

    $colors = ['#DC2626','#2563EB','#059669','#D97706','#7C3AED','#DB2777','#0891B2','#4F46E5','#EA580C','#65A30D'];
    $color = $colors[crc32($slug) % count($colors)];
    $initials = mb_substr($name, 0, 2);
    return '<svg viewBox="0 0 64 64" width="'.$size.'" height="'.$size.'"><circle cx="32" cy="32" r="30" fill="'.$color.'"/><text x="32" y="41" text-anchor="middle" fill="#fff" font-size="20" font-weight="bold" font-family="Arial">'.$initials.'</text></svg>';
}